# Generated by Django 5.0.4 on 2024-04-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_orderposition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderposition", name="quantity", field=models.IntegerField(),
        ),
    ]
